services:
  epivar-server:
    user: $USER:$USER
    image: ghcr.io/c3g/epivar-server:latest
    networks:
      - epivar-server-net
      - epivar-redis-net
      - epivar-db-net
    environment:
      - NODE_ENV=production
      - IMPORT_MAX_P_VAL=0.05
      - LOW_COUNT_THRESHOLD=5
    volumes:
      - /path/to/about.md:/app/data/about.md  # about file
      - /path/to/input-files:/app/input-files  # input files directory
      - /path/to/ucsc.tracks:/app/data/ucsc.other-tracks.txt  # static track hub with other relevant tracks
  epivar-redis:
    image: redis:7.2
    networks:
      - epivar-redis-net
  epivar-db:
    image: postgres:16
    networks:
      - epivar-db-net

networks:
  epivar-server-net:
    driver: bridge
    internal: true
  epivar-redis-net:
    driver: bridge
    internal: true
  epivar-db-net:
    driver: bridge
    internal: true
