services:
  epivar-gateway:
    image: ghcr.io/c3g/epivar-browser-gateway:latest
    networks:
      - epivar-server-net
    # volumes: mergedTracks read only
  epivar-server:
    user: $USER:$USER
    image: ghcr.io/c3g/epivar-browser-server:latest
    networks:
      - epivar-server-net
      - epivar-redis-net
      - epivar-db-net
    environment:
      - NODE_ENV=production
      - IMPORT_MAX_P_VAL=0.05
      - LOW_COUNT_THRESHOLD=5
  epivar-redis:
    image: redis:7.2
    networks:
      - epivar-redis-net
  epivar-db:
    image: postgres:16
    networks:
      - epivar-db-net

networks:
  epivar-server-net:
    driver: bridge
    internal: true
  epivar-redis-net:
    driver: bridge
    internal: true
  epivar-db-net:
    driver: bridge
    internal: true
