services:
  epivar-server:
    user: $USER:$USER
    image: ghcr.io/c3g/epivar-server:latest
    networks:
      - epivar-server-net
      - epivar-redis-net
      - epivar-db-net
    env_file:
      - ./example.secrets.env
    environment:
      - NODE_ENV=production
      - EPIVAR_REDIS_CONNECTION=redis://epivar-redis:6379
      - EPIVAR_IMPORT_MAX_P_VAL=0.05
      - EPIVAR_LOW_COUNT_THRESHOLD=5
    volumes:
      # dataset configuration: about Markdown file and EpiVar config.js
      - /path/to/about.md:/app/data/about.md  # about file
      - /path/to/config.js:/app/config.js  # dataset configuration file, see config.example.js
      # genotypes: VCF + index file
      - /path/to/genotypes.vcf.gz:/app/data/genotypes.vcf.gz:ro
      - /path/to/genotypes.vcf.gz.tbi:/app/data/genotypes.vcf.gz.tbi:ro
      # TODO
      - /path/to/input-files:/app/input-files  # input files directory
      - /path/to/ucsc.tracks:/app/data/ucsc.other-tracks.txt  # static track hub with other relevant tracks
      # tracks: sample bigWigs and writeable volume for on-the-fly merged tracks
      - /path/to/tracks:/tracks
      - volumes/mergedTracks:/mergedTracks

  epivar-redis:
    image: redis:7.2
    networks:
      - epivar-redis-net
    volumes:
      - volumes/redis:/data

  epivar-db:
    image: postgres:16
    networks:
      - epivar-db-net
    volumes:
      - volumes/db:/var/lib/postgresql/data

networks:
  epivar-server-net:
    driver: bridge
    internal: true
  epivar-redis-net:
    driver: bridge
    internal: true
  epivar-db-net:
    driver: bridge
    internal: true
