services:

  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"
    volumes:
      # Put Redis configuration + transient Redis config files on the normal VM filesystem
      - "/opt/varwig/stack/redis-conf:/usr/local/etc/redis"
      # Put persistent Redis data on the JBOD volume in the VM
      - "/flu-infection-data/redis:/data"

  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      # Nest PGDATA in Postgres /var/lib/... folder as recommended by Postgres Docker container README
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_PASSWORD: "replace-me"
    volumes:
      # Put Postgres data on the JBOD volume in the VM
      - "/flu-infection-data/postgres:/var/lib/postgresql/data"
