services:
  # Common -------------------------------------------------------------------------------------------------------------

  epivar-gateway:
    image: nginx:1.25-bookworm
    ports:
      - 8080:80
    depends_on:
      - epivar-portal
      - epivar-node-1-server
#      - epivar-node-2-server
    networks:
      - epivar-portal-net
      - epivar-node-1-server-net
#      - epivar-node-2-server-net

  epivar-portal:
    user: $UID:$UID
    image: ghcr.io/c3g/epivar-portal:pr-13
    networks:
      - epivar-portal-net
    env_file: portal.env
    volumes:
      - /etc/passwd:/etc/passwd:ro

  # Node 1: hg19 data --------------------------------------------------------------------------------------------------

  epivar-node-1-server:
    user: $UID:$UID
    image: ghcr.io/c3g/epivar-server:pr-13
    networks:
      - epivar-node-1-server-net
      - epivar-node-1-redis-net
      - epivar-node-1-db-net
    depends_on:
      - epivar-node-1-redis
      - epivar-node-1-db
    env_file:
      - ./node1/secrets.env
    environment:
      - NODE_ENV=production
      - EPIVAR_REDIS_CONNECTION=redis://epivar-node-1-redis:6379
      - EPIVAR_IMPORT_MAX_P_VAL=0.05
      - EPIVAR_LOW_COUNT_THRESHOLD=5
    volumes:
      # user information
      - /etc/passwd:/etc/passwd:ro
      # dataset configuration: about Markdown file, EpiVar config.js
      - ./node1/about.md:/app/data/about.md
      - ./node1/config.js:/app/config.js:ro
      # genotypes: VCF + index file
      - /flu-infection-data/node1/allSamples.hc.vqsr.mil.snpId.snpeff.dbnsfp.vcf.gz:/app/data/genotypes.vcf.gz:ro
      - /flu-infection-data/node1/allSamples.hc.vqsr.mil.snpId.snpeff.dbnsfp.vcf.gz.tbi:/app/data/genotypes.vcf.gz.tbi:ro
      # peaks files
      - /flu-infection-data/node1/matrices:/app/input-files/matrices:ro
      - /flu-infection-data/node1/qtls:/app/input-files/qtls:ro
      # tracks:
      #  - metadata JSON file,
      - ./node1/metadata.json:/app/data/metadata.json:ro
      #  - sample bigWigs,
      - /flu-infection-data/ATACseq:/tracks/ATACseq:ro
      - /flu-infection-data/H3K27ac:/tracks/H3K27ac:ro
      - /flu-infection-data/H3K27me3:/tracks/H3K27me3:ro
      - /flu-infection-data/H3K4me1:/tracks/H3K4me1:ro
      - /flu-infection-data/H3K4me3:/tracks/H3K4me3:ro
      - /flu-infection-data/RNAseq:/tracks/RNAseq:ro
      #  - writeable volume for on-the-fly merged tracks,
      - /flu-infection-data/node1/mergedTracks:/mergedTracks
      #  - other static tracks for showing in the UCSC browser.
      - ./node1/ucsc.other-tracks.txt:/app/data/ucsc.other-tracks.txt:ro

  epivar-node-1-redis:
    image: redis:7.2
    networks:
      - epivar-node-1-redis-net
    volumes:
      - ./node1/volumes/redis:/data

  epivar-node-1-db:
    image: postgres:16
    networks:
      - epivar-node-1-db-net
    env_file:
      - node1/secrets.env
    volumes:
      - ./node1/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./node1/volumes/db:/var/lib/postgresql/data

  # Node 2: hg38 data (lifted over) ------------------------------------------------------------------------------------

  # epivar-node-2-server:
  #   user: $USER:$USER
  #   image: ghcr.io/c3g/epivar-server:latest
  #   networks:
  #     - epivar-node-2-server-net
  #     - epivar-node-2-redis-net
  #     - epivar-node-2-db-net
  #   depends_on:
  #     - epivar-node-2-redis
  #     - epivar-node-2-db
  #   env_file:
  #     - ./node2/secrets.env
  #   environment:
  #     - NODE_ENV=production
  #     - EPIVAR_REDIS_CONNECTION=redis://epivar-node-2-redis:6379
  #     - EPIVAR_IMPORT_MAX_P_VAL=0.05
  #     - EPIVAR_LOW_COUNT_THRESHOLD=5
  #   volumes:
  #     # user information
  #     - /etc/passwd:/etc/passwd:ro
  #     # dataset configuration: about Markdown file, EpiVar config.js, tracks metadata.json
  #     - ./node2/about.md:/app/data/about.md
  #     - ./node2/config.js:/app/config.js:ro
  #     # genotypes: VCF + index file
  #     - /flu-infection-data/node2/allSamples.hc.vqsr.mil.snpId.snpeff.dbnsfp.GRCh38.vcf.gz:/app/data/genotypes.vcf.gz:ro
  #     - /flu-infection-data/node2/allSamples.hc.vqsr.mil.snpId.snpeff.dbnsfp.GRCh38.vcf.gz.tbi:/app/data/genotypes.vcf.gz.tbi:ro
  #     # peaks files
  #     - /flu-infection-data/node2/matrices:/app/input-files/matrices:ro
  #     - /flu-infection-data/node2/qtls:/app/input-files/qtls:ro
  #     # tracks:
  #     #  - metadata JSON file,
  #     - node1/metadata.json:/app/data/metadata.json:ro
  #     #  - sample bigWigs,
  #     - /flu-infection-data/node1/tracks:/tracks:ro
  #     #  - writeable volume for on-the-fly merged tracks,
  #     - /flu-infection-data/node1/mergedTracks:/mergedTracks
  #     #  - other static tracks for showing in the UCSC browser.
  #     #    *** NONE FOR NODE 2 ***
  #
  # epivar-node-2-redis:
  #   image: redis:7.2
  #   networks:
  #     - epivar-node-2-redis-net
  #   volumes:
  #     - node2/volumes/redis:/data
  #
  # epivar-node-2-db:
  #   image: postgres:16
  #   networks:
  #     - epivar-node-2-db-net
  #   env_file:
  #     - ./node2/secrets.env
  #   volumes:
  #     - ./node2/postgresql.conf:/etc/postgresql/postgresql.conf:ro
  #     - ./node2/volumes/db:/var/lib/postgresql/data

  # --------------------------------------------------------------------------------------------------------------------

networks:
  epivar-portal-net:
    driver: bridge
    internal: true

  epivar-node-1-server-net:
    driver: bridge
    internal: true
  epivar-node-1-redis-net:
    driver: bridge
    internal: true
  epivar-node-1-db-net:
    driver: bridge
    internal: true

#  epivar-node-2-server-net:
#    driver: bridge
#    internal: true
#  epivar-node-2-redis-net:
#    driver: bridge
#    internal: true
#  epivar-node-2-db-net:
#    driver: bridge
#    internal: true
